// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgmhApvWMi6fzgSLYh64nUIUXnK-CJJw0',
    appId: '1:270304561393:web:b042ccff42a72204d44150',
    messagingSenderId: '270304561393',
    projectId: 'pis-house',
    authDomain: 'pis-house.firebaseapp.com',
    databaseURL: 'https://pis-house-default-rtdb.firebaseio.com',
    storageBucket: 'pis-house.firebasestorage.app',
    measurementId: 'G-BSSN21D9EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuoTbIPK9b-I0qHBCuBoLuACWKTNvHvYM',
    appId: '1:270304561393:android:b6e8eef8e095fb05d44150',
    messagingSenderId: '270304561393',
    projectId: 'pis-house',
    databaseURL: 'https://pis-house-default-rtdb.firebaseio.com',
    storageBucket: 'pis-house.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXrwQ4QUdq3_aXAMoYyJ65Fa2voMGENLI',
    appId: '1:270304561393:ios:02428bc83cc9b10dd44150',
    messagingSenderId: '270304561393',
    projectId: 'pis-house',
    databaseURL: 'https://pis-house-default-rtdb.firebaseio.com',
    storageBucket: 'pis-house.firebasestorage.app',
    iosBundleId: 'com.example.pisHouseFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXrwQ4QUdq3_aXAMoYyJ65Fa2voMGENLI',
    appId: '1:270304561393:ios:02428bc83cc9b10dd44150',
    messagingSenderId: '270304561393',
    projectId: 'pis-house',
    databaseURL: 'https://pis-house-default-rtdb.firebaseio.com',
    storageBucket: 'pis-house.firebasestorage.app',
    iosBundleId: 'com.example.pisHouseFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgmhApvWMi6fzgSLYh64nUIUXnK-CJJw0',
    appId: '1:270304561393:web:01b872dccde591d4d44150',
    messagingSenderId: '270304561393',
    projectId: 'pis-house',
    authDomain: 'pis-house.firebaseapp.com',
    databaseURL: 'https://pis-house-default-rtdb.firebaseio.com',
    storageBucket: 'pis-house.firebasestorage.app',
    measurementId: 'G-N4310PX3R4',
  );
}
