// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqRMcVzkIB2VE0mLTDbaLKWWTcPuO7_nY',
    appId: '1:376004147659:web:84a929098d0d3133121e4e',
    messagingSenderId: '376004147659',
    projectId: 'pis-house-3612e',
    authDomain: 'pis-house-3612e.firebaseapp.com',
    storageBucket: 'pis-house-3612e.firebasestorage.app',
    measurementId: 'G-HZ3ZVF7SHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANbvHOmPxbBCzcWcCsZy2RAKsgfc5rcK8',
    appId: '1:376004147659:android:63baaed004823310121e4e',
    messagingSenderId: '376004147659',
    projectId: 'pis-house-3612e',
    storageBucket: 'pis-house-3612e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCaHLV5GgqnkDShZX2jswmOeEW0QDWOs',
    appId: '1:376004147659:ios:4d9424e383a05d38121e4e',
    messagingSenderId: '376004147659',
    projectId: 'pis-house-3612e',
    storageBucket: 'pis-house-3612e.firebasestorage.app',
    iosBundleId: 'com.example.pisHouseFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCaHLV5GgqnkDShZX2jswmOeEW0QDWOs',
    appId: '1:376004147659:ios:4d9424e383a05d38121e4e',
    messagingSenderId: '376004147659',
    projectId: 'pis-house-3612e',
    storageBucket: 'pis-house-3612e.firebasestorage.app',
    iosBundleId: 'com.example.pisHouseFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqRMcVzkIB2VE0mLTDbaLKWWTcPuO7_nY',
    appId: '1:376004147659:web:a58fe86e5ecbbea2121e4e',
    messagingSenderId: '376004147659',
    projectId: 'pis-house-3612e',
    authDomain: 'pis-house-3612e.firebaseapp.com',
    storageBucket: 'pis-house-3612e.firebasestorage.app',
    measurementId: 'G-4P52F99GRW',
  );

}